# Generated by Django 3.2.12 on 2023-07-02 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serialno', models.CharField(blank=True, max_length=250, null=True, verbose_name='Serial No')),
                ('issuingdate', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('validtill', models.DateField(blank=True, null=True, verbose_name='Valid Till')),
                ('createddate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
