# Generated by Django 3.2.12 on 2023-07-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='serialno',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Serial No'),
        ),
    ]
